# Generated by Django 3.2 on 2021-05-18 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auto_Daily_Strength',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendence_date', models.DateField()),
                ('second_year_present', models.IntegerField()),
                ('third_year_present', models.IntegerField()),
                ('final_year_present', models.IntegerField()),
                ('staffs_present', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Auto_notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dated_on', models.DateTimeField()),
                ('summary', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('attachements', models.FileField(upload_to='', verbose_name='uploades/auto/')),
            ],
        ),
        migrations.CreateModel(
            name='AutoTopper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank1', models.CharField(max_length=64)),
                ('rank2', models.CharField(max_length=64)),
                ('rank3', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='College_notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dated_on', models.DateTimeField()),
                ('summary', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('attachements', models.FileField(upload_to='uploades/')),
            ],
        ),
        migrations.CreateModel(
            name='Cse_Daily_Strength',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendence_date', models.DateField(auto_now_add=True)),
                ('second_year_present', models.IntegerField()),
                ('third_year_present', models.IntegerField()),
                ('final_year_present', models.IntegerField()),
                ('staffs_present', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Cse_notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dated_on', models.DateTimeField()),
                ('summary', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('attachements', models.FileField(upload_to='', verbose_name='uploades/cse/')),
            ],
        ),
        migrations.CreateModel(
            name='CseTopper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank1', models.CharField(max_length=64)),
                ('rank2', models.CharField(max_length=64)),
                ('rank3', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Department_Details_onlyA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_Year', models.DateField()),
                ('secondYearCse', models.IntegerField()),
                ('thirdYearCse', models.IntegerField()),
                ('finalYearCse', models.IntegerField()),
                ('total_Cse_staffs', models.IntegerField()),
                ('secondYearEee', models.IntegerField()),
                ('thirdYearEee', models.IntegerField()),
                ('finalYearEee', models.IntegerField()),
                ('total_Eee_staffs', models.IntegerField()),
                ('secondYearAuto', models.IntegerField()),
                ('thirdYearAuto', models.IntegerField()),
                ('finalYearAuto', models.IntegerField()),
                ('total_Auto_staffs', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_code', models.IntegerField()),
                ('department_name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Eee_Daily_Strength',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendence_date', models.DateField()),
                ('second_year_present', models.IntegerField()),
                ('third_year_present', models.IntegerField()),
                ('final_year_present', models.IntegerField()),
                ('staffs_present', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Eee_notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dated_on', models.DateTimeField()),
                ('summary', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('attachements', models.FileField(upload_to='', verbose_name='uploades/eee/')),
            ],
        ),
        migrations.CreateModel(
            name='EeeTopper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank1', models.CharField(max_length=64)),
                ('rank2', models.CharField(max_length=64)),
                ('rank3', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Topper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank1', models.CharField(max_length=64)),
                ('rank2', models.CharField(max_length=64)),
                ('rank3', models.CharField(max_length=64)),
                ('rank1_dep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rank1_name', to='department.departments')),
                ('rank2_dep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rank2_name', to='department.departments')),
                ('rank3_dep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rank3_name', to='department.departments')),
            ],
        ),
    ]
