# Generated by Django 3.2 on 2021-05-12 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='College_notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dated_on', models.DateTimeField()),
                ('summary', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('attachements', models.FileField(upload_to='')),
            ],
        ),
    ]
