# Generated by Django 3.2 on 2021-05-18 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto_daily_strength',
            name='attendence_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='cse_daily_strength',
            name='attendence_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='eee_daily_strength',
            name='attendence_date',
            field=models.DateTimeField(),
        ),
    ]
