# Generated by Django 3.2.3 on 2021-05-23 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0002_auto_20210518_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto_notification',
            name='attachements',
            field=models.FileField(upload_to='uploades/auto/'),
        ),
        migrations.AlterField(
            model_name='college_notification',
            name='attachements',
            field=models.FileField(upload_to='uploades/college/'),
        ),
        migrations.AlterField(
            model_name='cse_notification',
            name='attachements',
            field=models.FileField(upload_to='uploades/cse/'),
        ),
        migrations.AlterField(
            model_name='eee_notification',
            name='attachements',
            field=models.FileField(upload_to='uploades/eee/'),
        ),
    ]
