# Generated by Django 3.2 on 2021-05-12 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0002_college_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auto_notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dated_on', models.DateTimeField()),
                ('summary', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('attachements', models.FileField(upload_to='', verbose_name='uploades/auto/')),
            ],
        ),
        migrations.CreateModel(
            name='Cse_notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dated_on', models.DateTimeField()),
                ('summary', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('attachements', models.FileField(upload_to='', verbose_name='uploades/cse/')),
            ],
        ),
        migrations.CreateModel(
            name='Eee_notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dated_on', models.DateTimeField()),
                ('summary', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('attachements', models.FileField(upload_to='', verbose_name='uploades/eee/')),
            ],
        ),
        migrations.AlterField(
            model_name='college_notification',
            name='attachements',
            field=models.FileField(upload_to='uploades/'),
        ),
    ]
